language: python
python:
  - "3.4"
  - "3.5"
env:
  - DJANGO="Django==1.9"
  - DJANGO="Django==1.10"
install:
  - pip install -q $DJANGO
  - pip install -r requirements.txt
  - python setup.py -q install
before_script:
  - psql -c 'create database disbidb;' -U postgres
database:
  - postgres service
script:
  - python tests/manage.py test core
