# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-15 14:03
# future
from __future__ import unicode_literals

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checksum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=512)),
                ('checksum', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.RunSQL(
            # Create the neccessary pgSQL function.
            '''CREATE OR REPLACE FUNCTION divide_without_zeroerr(a float, b float) RETURNS float AS $$
            BEGIN
                IF b = 0 THEN
            RETURN NULL;
             ELSE
              RETURN a/b;
             END IF;
            END;
            $$ LANGUAGE PLPGSQL;'''
        ),
    ]
